spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0

simbot:
  core:
    bot-resource-type: resource_first
  component:
    mirai:
      message:
        cache:
          enable: true
      device-info-file: src/main/resources/device.json