spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: username
    password: password
    url: url
  redis:
    host: localhost
    port: 6379
    database: 0

des:
  key: 1,2,3,4,5,6,7,8